# Generated by Django 5.0.6 on 2026-03-25 01:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_id', models.UUIDField()),
                ('dataset_nom', models.CharField(max_length=255)),
                ('titre', models.CharField(default='Mon dashboard', max_length=255)),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_widget', models.CharField(choices=[('bar', 'Barres'), ('line', 'Lignes'), ('pie', 'Camembert'), ('scatter', 'Nuage de points'), ('histogram', 'Histogramme'), ('heatmap', 'Heatmap'), ('table', 'Tableau'), ('carte', 'Carte')], max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('variable_x', models.CharField(max_length=255)),
                ('variable_y', models.CharField(blank=True, max_length=255)),
                ('filtres', models.JSONField(default=dict)),
                ('config', models.JSONField(default=dict)),
                ('position', models.IntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboard_app.dashboard')),
            ],
            options={
                'db_table': 'widgets',
                'ordering': ['position'],
            },
        ),
    ]
