# Generated by Django 5.0.6 on 2026-03-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='widget',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='widget',
            name='filtres',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='widget',
            name='type_widget',
            field=models.CharField(choices=[('bar', 'Barres'), ('line', 'Lignes'), ('pie', 'Camembert'), ('scatter', 'Nuage de points'), ('histogram', 'Histogramme'), ('heatmap', 'Heatmap'), ('table', 'Tableau'), ('carte', 'Carte Folium')], max_length=20),
        ),
    ]
