# Generated by Django 5.0.6 on 2026-03-25 01:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarteGeneree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_id', models.UUIDField()),
                ('dataset_nom', models.CharField(max_length=255)),
                ('type_carte', models.CharField(choices=[('choropletre', 'Choroplèthe'), ('heatmap', 'Carte de chaleur'), ('points', 'Carte de points'), ('comparaison', 'Comparaison 2 variables')], max_length=20)),
                ('variable', models.CharField(max_length=255)),
                ('colonne_geo', models.CharField(blank=True, max_length=255)),
                ('annee', models.CharField(blank=True, max_length=10, null=True)),
                ('config', models.JSONField(default=dict)),
                ('html_carte', models.TextField(blank=True)),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cartes_generees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeoJSONRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('niveau', models.CharField(max_length=50)),
                ('cle_join', models.CharField(max_length=100)),
                ('geojson', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'geojson_regions',
            },
        ),
    ]
