# Generated by Django 6.0.3 on 2026-03-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonneinfo',
            name='exemple_valeurs',
            field=models.JSONField(blank=True, default=list, help_text='3-5 exemples de valeurs pour aperçu'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='donnees_json',
            field=models.JSONField(blank=True, default=list, help_text='Données nettoyées stockées en JSON pour export/consultation'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='rapport_nettoyage',
            field=models.JSONField(blank=True, default=dict, help_text='Rapport JSON : doublons, lignes vides, encodage, etc.'),
        ),
        migrations.AlterField(
            model_name='exportlog',
            name='chemin_fichier',
            field=models.CharField(blank=True, help_text='Chemin du fichier exporté sur le serveur', max_length=500),
        ),
        migrations.AlterField(
            model_name='traitementlog',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text="Détails JSON : ex. {'avant': 1200, 'apres': 1185, 'diff': 15}"),
        ),
        migrations.AlterField(
            model_name='traitementlog',
            name='snapshot_avant',
            field=models.JSONField(blank=True, default=list, help_text='Snapshot JSON des données avant cette modification'),
        ),
    ]
